comment:
  image:
    repository: donasktello/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: donasktello/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: donasktello/ui
    tag: latest
    service:
      externalPort: 9292
