global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#viacheslav_shvetsov'
