kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: rw1qwRWzhs23m6VhdLgq14sr6fV35FuvYXCax/wlGSs=
      - identity: {}
